#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Executando lint, build e testes antes do commit..."
npm run lint && npm run build && npm test
if [ $? -ne 0 ]; then
  echo "❌ Lint, build ou testes falharam. Commit cancelado."
  exit 1
fi
echo "✅ Lint, build e testes passaram com sucesso!"
